src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('gestion/', include("gestion.urls")),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path
from .views import (inicio, index, about, CustomLoginView, CustomRegisterView, UpdateProfileViwe)
from django.contrib.auth.views import LogoutView


app_name = "core"

urlpatterns = [
    path('', inicio, name='inicio'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('profile/', UpdateProfileViwe.as_view(), name='perfil'),
    path('logout', LogoutView.as_view(template_name="core/logout.html"), name='logout'),
    path('index/', index, name='index'),
    path('about/', about, name='about'),

]

src/gestion/urls.py
from django.urls import path
from .views_models import transaccion, usuario, informe

app_name = "gestion"

urlpatterns = [
    path("usuario/list/", usuario.UsuarioListView.as_view(), name="usuario_list"),
    path("usuario/create/", usuario.UsuarioCreateView.as_view(), name="usuario_create"),
    path("usuario/update/<int:pk>", usuario.UsuarioUpdateView.as_view(), name="usuario_update"),
    path("usuario/detail/<int:pk>", usuario.UsuarioDetailView.as_view(), name="usuario_detail"),
    path("usuario/delete/<int:pk>/", usuario.UsuarioDeleteView.as_view(), name="usuario_delete"),
    ]

urlpatterns += [
    path("transaccion/list/", transaccion.TransaccionListView.as_view(), name="transaccion_list"),
    path("transaccion/create/", transaccion.TransaccionCreateView.as_view(), name="transaccion_create"),
    path("transaccion/update/<int:pk>", transaccion.TransaccionUpdateView.as_view(), name="transaccion_update"),
    path("transaccion/detail/<int:pk>", transaccion.TransaccionDetailView.as_view(), name="transaccion_detail"),
    path("transaccion/delete/<int:pk>", transaccion.TransaccionDeleteView.as_view(), name="transaccion_delete"),]

urlpatterns += [
    path("informe/list/", informe.InformeListView.as_view(), name="informe_list"),
    path("informe/create/", informe.InformeCreateView.as_view(), name="informe_create"),
    path("informe/update/<int:pk>", informe.InformeUpdateView.as_view(), name="informe_update"),
    path("informe/detail/<int:pk>", informe.InformeDetailView.as_view(), name="informe_detail"),
    path("informe/delete/<int:pk>/", informe.InformeDeleteView.as_view(), name="informe_delete"),
    ]

src/gestion/models.py
from django.db import models
from datetime import datetime, date
from django.contrib.auth.models import User
from django.db.models import Sum
from calendar import monthrange
from django.core.exceptions import ValidationError

TIPOS_TRANSACCIONES =[("I","Ingreso"),("G","Gasto")]

CATEGORIAS = [("A","Alimentos"),
             ("AS","Alquiler y Servicios"),
             ("S","Shopping"),
             ("R","Regalos"),
             ("E","Entretenimiento"),
             ("V","Viajes"),
             ("S","Sueldo"),
             ("O","Otros")]

TIPOS_INFORME = [
        ('ING', 'Ingreso'),
        ('GAS', 'Gasto'),
        ('BAL', 'Balance General'),
    ]

PERIODOS = [
        ('MENSUAL', 'Mensual'),
        ('TRIMESTRAL', 'Trimestral'),
        ('SEMESTRAL', 'Semestre'),
        ('ANUAL', 'Anual'),
    ]

class Usuario(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name='Usuario')
    dni = models.IntegerField(unique=True,null=True)
    fecha_nacimiento = models.DateField()
    foto = models.ImageField(upload_to='imagenes_perfil', blank=True, null=True)

    @property
    def calcular_edad(self):
        hoy = datetime.today()
        if hoy.month < self.fecha_nacimiento.month:
            edad = hoy.year - self.fecha_nacimiento.year -1
        else:
            edad = hoy.year - self.fecha_nacimiento.year
        return edad

    def __str__(self):
        return self.usuario.username

class Transaccion(models.Model):
    nombre = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    tipo = models.CharField(max_length=1,choices=TIPOS_TRANSACCIONES)
    monto = models.DecimalField(max_digits=10,decimal_places=2)
    categoria = models.CharField(max_length=50,choices=CATEGORIAS,default="O")
    descripcion = models.TextField(max_length=30,null=True,blank=True)
    fecha = models.DateField(null=True,blank=True)

    class Meta:
        verbose_name = "Transaccion"
        verbose_name_plural = "Transacciones"
        ordering = ("-fecha",)

class Informe(models.Model):
    nombre = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    año = models.PositiveIntegerField()
    informe = models.CharField(max_length=25)
    tipo = models.CharField(max_length=3,choices=TIPOS_INFORME,default='BAL')
    periodo = models.CharField(max_length=10,choices=PERIODOS,default='ANUAL')
    mes_inicio = models.PositiveIntegerField(default=1)  
    mes_fin = models.PositiveIntegerField(default=12)    

    class Meta():
        unique_together = ("año","tipo","periodo","mes_inicio","mes_fin")

    def clean(self):
        """Valida que mes_inicio y mes_fin sean valores lógicos."""
        if self.mes_inicio and self.mes_fin:
            if not (1 <= self.mes_inicio <= 12) or not (1 <= self.mes_fin <= 12):
                raise ValidationError("Los meses deben estar entre 1 y 12.")
            if self.mes_inicio > self.mes_fin:
                raise ValidationError("El mes de inicio no puede ser mayor que el mes final.")

    def calcular_total_rango(self, inicio, fin):
        suma_ingresos = 0
        suma_gastos = 0
        suma_total = 0
        if self.tipo == 'ING':  # Ingresos
            total = Transaccion.objects.filter(
                nombre=self.nombre,
                tipo='I',
                fecha__range=[inicio, fin]
            )
            suma_total = total.aggregate(total=Sum('monto'))['total'] or 0
            return suma_total, 0, 0
        
        elif self.tipo == 'GAS':  # Gastos
            total = Transaccion.objects.filter(
                nombre=self.nombre,
                tipo='G',
                fecha__range=[inicio, fin]
            )
            suma_total = total.aggregate(total=Sum('monto'))['total'] or 0
            return 0, suma_total, 0
        
        elif self.tipo == 'BAL':  # Balance
            ingresos = Transaccion.objects.filter(
                nombre=self.nombre,
                tipo='I',
                fecha__range=[inicio, fin]
            )
            suma_ingresos = ingresos.aggregate(total=Sum('monto'))['total'] or 0
            gastos = Transaccion.objects.filter(
                nombre=self.nombre,
                tipo='G',
                fecha__range=[inicio, fin]
            )
            suma_gastos = gastos.aggregate(total=Sum('monto'))['total'] or 0
            suma_total = suma_ingresos- suma_gastos
            return suma_ingresos, suma_gastos, suma_total
        else:
            return 0,0,0
    
    def calcular_totales_mensuales(self):
        totales = []
        for mes in range(self.mes_inicio, self.mes_fin + 1):
            inicio_mes = date(self.año, mes, 1)
            _, fin_dia = monthrange(self.año, mes)
            fin_mes = date(self.año, mes, fin_dia)

            ingresos, gastos, total = self.calcular_total_rango(inicio_mes, fin_mes)
            totales.append((inicio_mes.strftime("%b %Y"), ingresos, gastos, total))
        return totales

src/gestion/forms.py
from django import forms

from .models import Usuario, Transaccion, Informe


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = "__all__"
        widgets = {
            "fecha_nacimiento": forms.DateInput(attrs={"type": "date"}),
        }


class TransaccionForm(forms.ModelForm):
    class Meta:
        model = Transaccion
        fields = "__all__"
        widgets = {
            "fecha": forms.DateInput(attrs={"type": "date"}),
        }
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        # Si el usuario no es staff, predefinir el campo 'nombre' con el usuario actual
        if not user.is_staff:
            self.fields['nombre'].initial = user  # Establecer el usuario actual
            self.fields['nombre'].widget.attrs['readonly'] = 'readonly'  # Hacer el campo no editable


class InformeForm(forms.ModelForm):
    class Meta:
        model = Informe
        fields = "__all__"
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        # Si el usuario no es staff, predefinir el campo 'nombre' con el usuario actual
        if not user.is_staff:
            self.fields['nombre'].initial = user  # Establecer el usuario actual
            self.fields['nombre'].widget.attrs['readonly'] = 'readonly'  # Hacer el campo no editable

src/gestion/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

def index(request: HttpRequest) -> HttpResponse:
    return render(request, "gestion/index.html")

def about(request: HttpRequest) -> HttpResponse:
    return render(request,"gestion/about.html")

src/gestion/templates/gestion/index.html
{% extends 'gestion/base.html' %}

{% block contenido %}
    <main >
        <h1>Bienvenido</h1>
        <a href="{% url 'gestion:usuario_list' %}"><button>Mostrar Usuarios</button></a>
        <a href="{% url 'gestion:transaccion_list' %}"><button>Mostrar Transacciones</button></a>
        <a href="{% url 'gestion:informe_list' %}"><button>Mostrar Informes</button></a>
    </main>
{% endblock contenido %}

src/gestion/templates/gestion/informe_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            <h4 class="display-4 mb-4">Eliminar Informe</h4>
            <p>¿Está seguro que desea eliminar el informe {{object.informe}} de {{object.nombre}}?</p>
        </div>
        <div class="col-lg-8 text-center">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary mt-2" style="background-color: black; border-color: black;">Sí, confirmo</button>
                <a href="{% url 'gestion:informe_list' %}" class="btn btn-primary mt-2" style="background-color: lightgreen; border-color: lightgreen; color: black; text-decoration: none; padding-left: 30px; padding-right: 30px;">Volver a Informe</a>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}

src/gestion/templates/gestion/informe_delete.html
{% extends 'core/base.html' %}

{% block contenido %}
    <h1>Eliminar Informe</h1>
    <p>¿Está seguro que desea eliminar el informe {{object.name}}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Si, confirmo</button>
    </form>

    <a href="{% url 'gestion:informe_list' %}"><button>Volver a Informes</button></a>
{% endblock contenido %}

src/gestion/templates/gestion/informe_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}


{% block contenido %}

<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            <h4 class="display-4 mb-4">Detalle del Informe</h4>
        </div>

        <div class="container px-4 px-lg-5 my-5">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <strong>Nombre:</strong> {{ object.nombre }}
                        </li>
                        <li class="list-group-item">
                            <strong>Año:</strong> {{ object.año }}
                        </li>
                        <li class="list-group-item">
                            <strong>Informe:</strong> {{ object.informe }}
                        </li>
                        <li class="list-group-item">
                            <strong>Período:</strong> {{ object.get_periodo_display}}
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div>
            {% if etiquetas and total %}
                <h3 style="text-align: center;">Gráfico de {{ object.informe }}</h3>
                <canvas id="grafico" width="400" height="100"></canvas>

                <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                <script>
                    const ctx = document.getElementById('grafico').getContext('2d');
                
                    const etiqueta = {{etiquetas|safe }};
                    const totales = {{total|safe}};
                    const ingreso = {{ingresos|safe}};
                    const gasto = {{gastos|safe}};
                
                    const data = {
                        labels: etiqueta,
                        datasets: [
                            {
                            label: 'Ingresos por {{ object.get_periodo_display }}',
                            data: ingreso,
                            backgroundColor: 'rgba(54, 162, 235, 0.3)',
                            borderColor: 'rgba(54, 162, 235, 1)',
                            borderWidth: 1
                            },
                            {
                            label: 'Gastos por {{ object.get_periodo_display }}',
                            data: gasto,
                            backgroundColor: 'rgba(255, 99, 132, 0.3)',
                            borderColor: 'rgba(255, 99, 132, 1)',
                            borderWidth: 1
                            },
                            {
                            label: 'Totales por {{ object.get_periodo_display }}',
                            data: totales,
                            backgroundColor: 'rgba(138, 43, 226, 0.3)',
                            borderColor: 'rgba(138, 43, 226, 1)',
                            borderWidth: 1
                            }
                    ]
                    };
                
                    new Chart(ctx, {
                        type: 'bar',
                        data: data,
                        options: {
                            scales: {
                                y: {
                                    beginAtZero: true
                                }
                            }
                        }
                    });
                </script>
            {% else %}
                <p>No hay datos disponibles para mostrar en el gráfico.</p>
            {% endif %}
        </div>
        
        <div class="col-lg-8 mt-4">
            <a href="{% url 'gestion:informe_list' %}" class="btn btn-primary mt-2" style="background-color: lightgreen; border-color: lightgreen; color: black; padding-left: 30px; padding-right: 30px;">Volver a Informes</a>
        </div>

    </div>
</div>           
{% endblock contenido %}

src/gestion/templates/gestion/informe_form.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            {% if form.instance.pk %}
            <h4 class="display-4 mb-4">Modificar Informe</h4>
            {% else %}
            <h4 class="display-4 mb-4">Crear Informe</h4>
            {% endif %}
        </div>

        <div class="container px-4 px-lg-5">
            <form method="POST" enctype="multipart/form-data" class="mx-3" style="max-width: 600px;">
                {% csrf_token %}
                <div class="row g-3">
                    {% for field in form %}
                    <div class="col-md-4">
                        <label for="{{ field.id_for_label }}" class="form-label fw-bold ms-5">{{ field.label }}</label>
                    </div>
                    <div class="col-md-6">
                        {{ field }}
                        {% if field.help_text %}
                        <div class="form-text">{{ field.help_text }}</div>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                <div class="d-flex justify-content-between mt-4 mx-5">
                    <button type="submit" class="btn btn-primary" style="background-color: black; border-color: black;">Guardar</button>

                    <a href="{% url 'gestion:informe_list' %}" class="btn btn-primary" style="background-color: lightgreen; border-color: lightgreen; color: black; text-decoration: none; padding: 5px 20px;">
                        Volver a Informes
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contenido %}

src/gestion/templates/gestion/informe_list.html
{% extends 'core/base.html' %}
{% load static %}


{% block contenido %}

<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            <h4 class="display-4 mb-4">Lista de Informes</h4>
        </div>

        <div class="col-lg-8">
            <a href="{% url 'gestion:informe_create' %}" class="btn btn-primary mt-2" style="background-color: lightgreen; border-color: lightgreen; color: black; padding-left: 30px; padding-right: 30px;">Crear Informe</a>
        </div>

        <div class="col-lg-8 text-center mt-4">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Informe</th>
                            <th>Año</th>
                            <th>Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.nombre }}</td>
                                <td style="text-align: left;">{{ object.informe }}</td>
                                <td>{{ object.año }}</td>
                                <td>
                                    <a href="{% url 'gestion:informe_update' object.id %}" class="btn btn-warning btn-sm" style="background-color:lightgreen;border-color: lightgreen; color: black;">Editar</a>
                                    <a href="{% url 'gestion:informe_detail' object.id %}" class="btn btn-info btn-sm" style="background-color:lightgreen;border-color: lightgreen;color: black;">Ver</a>
                                    <a href="{% url 'gestion:informe_delete' object.id %}" class="btn btn-danger btn-sm" style="background-color: lightgreen;border-color: lightgreen;color: black;">Eliminar</a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center">No hay datos disponibles</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-8 mt-4">
            <a href="{% url 'core:index' %}" class="btn btn-primary mt-2" style="background-color: lightgreen; border-color: lightgreen; color: black; padding-left: 30px; padding-right: 30px;">Volver al inicio</a>
        </div>
    </div>
</div>

{% endblock contenido %}

src/gestion/templates/gestion/transaccion_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            <h4 class="display-4 mb-4">Eliminar Operación</h4>
            <p>¿Está seguro que desea eliminar la operación {{object.get_categoria_display}} del {{object.fecha}}?</p>
        </div>
        <div class="col-lg-8 text-center">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary mt-2" style="background-color: black; border-color: black;">Sí, confirmo</button>
                <a href="{% url 'gestion:transaccion_list' %}" class="btn btn-primary mt-2" style="background-color: lightblue; border-color: lightblue; color: black; text-decoration: none; padding-left: 30px; padding-right: 30px;">Volver a Operaciones</a>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}

src/gestion/templates/gestion/transaccion_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}


{% block contenido %}

<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            <h4 class="display-4 mb-4">Datos de la Operación</h4>
        </div>

        <div class="container px-4 px-lg-5 my-5">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <strong>Nombre:</strong> {{ object.nombre }}
                        </li>
                        <li class="list-group-item">
                            <strong>Operación:</strong> {{ object.get_tipo_display }}
                        </li>
                        <li class="list-group-item">
                            <strong>Monto:</strong> {{ object.monto|intcomma }}
                        </li>
                        <li class="list-group-item">
                            <strong>Fecha:</strong> {{ object.fecha }}
                        </li>
                        <li class="list-group-item">
                            <strong>Categoría:</strong> {{ object.get_categoria_display }}
                        </li>
                        <li class="list-group-item">
                            <strong>Descripción:</strong>
                                {% if object.descripcion %}
                                    {{ object.descripcion }}                        
                                {% else %}
                                    <em>Sin descripción</em>
                                {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="col-lg-8 mt-4">
            <a href="{% url 'gestion:transaccion_list' %}" class="btn btn-primary mt-2" style="background-color:lightblue; border-color:lightblue; color: black; padding-left: 30px; padding-right: 30px;">Volver a Operaciones</a>
        </div>

    </div>
</div>           

{% endblock contenido %}

src/gestion/templates/gestion/transaccion_form.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            {% if form.instance.pk %}
            <h4 class="display-4 mb-4">Modificar Operación</h4>
            {% else %}
            <h4 class="display-4 mb-4">Crear Operación</h4>
            {% endif %}
        </div>

        <div class="container px-4 px-lg-5">
            <form method="POST" enctype="multipart/form-data" class="mx-3" style="max-width: 600px;">
                {% csrf_token %}
                <div class="row g-3">
                    {% for field in form %}
                    <div class="col-md-4">
                        <label for="{{ field.id_for_label }}" class="form-label fw-bold ms-5">{{ field.label }}</label>
                    </div>
                    <div class="col-md-6">
                        {{ field }}
                        {% if field.help_text %}
                        <div class="form-text">{{ field.help_text }}</div>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                <div class="d-flex justify-content-between mt-4">
                    <button type="submit" class="btn btn-primary" style="background-color: black; border-color: black;">Guardar</button>

                    <a href="{% url 'gestion:transaccion_list' %}" class="btn btn-primary" style="background-color: lightblue; border-color: lightblue; color: black; text-decoration: none; padding: 5px 20px;">
                        Volver a Operaciones
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contenido %}

src/gestion/templates/gestion/transaccion_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}


{% block contenido %}

<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            <h4 class="display-4 mb-4">Lista de Operaciones</h4>
        </div>

        <div class="col-lg-8">
            <a href="{% url 'gestion:transaccion_create' %}" class="btn btn-primary mt-2" style="background-color: lightblue; border-color: lightblue; color: black; padding-left: 30px; padding-right: 30px;">Cargar Operación</a>
        </div>

        <div class="col-lg-8 text-center mt-4">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Transacciones</th>
                            <th>Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td style="text-align: left;">{{ object.nombre }} | {{ object.get_tipo_display}} | {{ object.monto|intcomma }} | {{ object.get_categoria_display }} </td>
                                <td>
                                    <a href="{% url 'gestion:transaccion_update' object.id %}" class="btn btn-warning btn-sm" style="background-color: lightblue;border-color:lightblue; color: black;">Editar</a>
                                    <a href="{% url 'gestion:transaccion_detail' object.id %}" class="btn btn-info btn-sm" style="background-color:lightblue;border-color:lightblue;color: black;">Ver</a>
                                    <a href="{% url 'gestion:transaccion_delete' object.id %}" class="btn btn-danger btn-sm" style="background-color:lightblue;border-color:lightblue;color: black;">Eliminar</a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center">No hay datos disponibles</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-8 mt-4">
            <a href="{% url 'core:index' %}" class="btn btn-primary mt-2" style="background-color: lightblue; border-color:lightblue; color: black; padding-left: 30px; padding-right: 30px;">Volver al inicio</a>
        </div>
    </div>
</div>

{% endblock contenido %}

src/gestion/templates/gestion/usuario_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            <h4 class="display-4 mb-4">Eliminar Usuario</h4>
            <p>¿Está seguro que desea eliminar el usuario {{object.usuario}}?</p>
        </div>
        <div class="col-lg-8 text-center">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary mt-2" style="background-color: black; border-color: black;">Sí, confirmo</button>
                <a href="{% url 'gestion:usuario_list' %}" class="btn btn-primary mt-2" style="background-color: plum; border-color: plum; color: black; text-decoration: none; padding-left: 30px; padding-right: 30px;">Volver a Miembros</a>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}

src/gestion/templates/gestion/usuario_list.html
{% extends 'core/base.html' %}
{% load static %}


{% block contenido %}

<div class="container px-4 px-lg-5">
    <div class="row justify-content-center my-5">
        <div class="col-lg-8 text-center">
            <h4 class="display-4 mb-4">Lista de Miembros</h4>
        </div>

        <div class="col-lg-8">
            <a href="{% url 'gestion:usuario_create' %}" class="btn btn-primary mt-2" style="background-color: plum; border-color: plum; color: black; padding-left: 30px; padding-right: 30px;">Crear Miembro</a>
        </div>

        <div class="col-lg-8 text-center mt-4">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>DNI</th>
                            <th>Edad</th>
                            <th>Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.usuario.username }}</td>
                                <td>{{ object.dni }}</td>
                                <td>{{ object.calcular_edad }}</td>
                                <td>
                                    <a href="{% url 'gestion:usuario_update' object.id %}" class="btn btn-warning btn-sm" style="background-color:plum;border-color: plum; color: black;">Editar</a>
                                    <a href="{% url 'gestion:usuario_detail' object.id %}" class="btn btn-info btn-sm" style="background-color:plum;border-color: plum;color: black;">Ver</a>
                                    <a href="{% url 'gestion:usuario_delete' object.id %}" class="btn btn-danger btn-sm" style="background-color: plum;border-color: plum;color: black;">Eliminar</a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center">No hay usuarios creados</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-8 mt-4">
            <a href="{% url 'core:index' %}" class="btn btn-primary mt-2" style="background-color: plum; border-color: plum; color: black; padding-left: 30px; padding-right: 30px;">Volver al inicio</a>
        </div>
    </div>
</div>

{% endblock contenido %}