src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('gestion/', include("gestion.urls")),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path
from .views import (inicio, index, about, CustomLoginView, CustomRegisterView, UpdateProfileViwe)
from django.contrib.auth.views import LogoutView


app_name = "core"

urlpatterns = [
    path('', inicio, name='inicio'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('profile/', UpdateProfileViwe.as_view(), name='perfil'),
    path('logout', LogoutView.as_view(template_name="core/logout.html"), name='logout'),
    path('index/', index, name='index'),
    path('about/', about, name='about'),

]

src/gestion/urls.py
from django.urls import path
from .views_models import transaccion, usuario, informe

app_name = "gestion"

urlpatterns = [
    path("usuario/list/", usuario.UsuarioListView.as_view(), name="usuario_list"),
    path("usuario/create/", usuario.UsuarioCreateView.as_view(), name="usuario_create"),
    path("usuario/update/<int:pk>", usuario.UsuarioUpdateView.as_view(), name="usuario_update"),
    path("usuario/detail/<int:pk>", usuario.UsuarioDetailView.as_view(), name="usuario_detail"),
    path("usuario/delete/<int:pk>/", usuario.UsuarioDeleteView.as_view(), name="usuario_delete"),
    ]

urlpatterns += [
    path("transaccion/list/", transaccion.TransaccionListView.as_view(), name="transaccion_list"),
    path("transaccion/create/", transaccion.TransaccionCreateView.as_view(), name="transaccion_create"),
    path("transaccion/update/<int:pk>", transaccion.TransaccionUpdateView.as_view(), name="transaccion_update"),
    path("transaccion/detail/<int:pk>", transaccion.TransaccionDetailView.as_view(), name="transaccion_detail"),
    path("transaccion/delete/<int:pk>", transaccion.TransaccionDeleteView.as_view(), name="transaccion_delete"),]

urlpatterns += [
    path("informe/list/", informe.InformeListView.as_view(), name="informe_list"),
    path("informe/create/", informe.InformeCreateView.as_view(), name="informe_create"),
    path("informe/update/<int:pk>", informe.InformeUpdateView.as_view(), name="informe_update"),
    path("informe/detail/<int:pk>", informe.InformeDetailView.as_view(), name="informe_detail"),
    path("informe/delete/<int:pk>/", informe.InformeDeleteView.as_view(), name="informe_delete"),
    ]

src/core/models.py
from django.db import models

# Create your models here.

src/core/forms.py
from typing import Any
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = AuthenticationForm
        fields = ['username','password']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {'username': ''}
    
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]

src/core/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm, CustomUserCreationForm, UserProfileForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_not_required
from django.utils.decorators import method_decorator

@login_not_required
def inicio(request: HttpRequest) -> HttpResponse:
    return render(request, "core/inicio.html")

def index(request: HttpRequest) -> HttpResponse:
    return render(request, "core/index.html")

@login_not_required
def about(request: HttpRequest) -> HttpResponse:
    return render(request,"core/about.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'core/login.html'
    success_url = reverse_lazy('core:index')

@method_decorator(login_not_required, name='dispatch')
class CustomRegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')

class UpdateProfileViwe(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/perfil.html'
    success_url = reverse_lazy('core:index') 
    def get_object(self):
        return self.request.user

src/core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
            <h1 class="display-4 mb-4">Acerca de mí</h1>
            <div class="mb-4">
                <img src="{% static 'core/img/perfil.jpg' %}" alt="Foto de perfil"
                     class="img-fluid rounded-circle shadow-lg" style="max-width: 200px;">
            </div>
            <p class="lead mb-4">¡Hola! Me llamo Aylen Poschner y soy Contadora Publica. Nunca había hecho nada de programación, asi que los invito a conocer mi primer proyecto!</p>
            
            <p class="lead mb-4">Este proyecto está inspirado en una planilla de Excel que llevaba cuando era chica para tener registro de mis ingresos y gastos y de su evolución.</p>
        </div>
    </div>
</div>
<div class="container py-5">
    <h5>Conecta Conmigo</h5>
    <p>Linkedin: <a href="https://www.linkedin.com/in/aylen-poschner" target="_blank">https://www.linkedin.com/in/aylen-poschner</a></p>
    <p>Repositorio del Proyecto: <a href="https://github.com/aylenposchner/Coderhouse-60095-AylenPoschner.git" target="_blank">https://github.com/aylenposchner/Coderhouse-60095-AylenPoschner.git</a></p>
</div>

<div class="container py-5">
    <h5>Acerca del Curso</h5>
    <p>Curso Corderhouse: Python</p>
    <p>Comisión: 60095</p>
    <P>Profesor: Esteban Acevedo</P>
    <p>Tutor: Nicolas Dziuma</p>
</div>
{% endblock contenido %}

src/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>GESTION FINANCIERA FAMILIAR</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %} " />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    </head>
    <body class="d-flex flex-column min-vh-100">
        <!-- Navbar -->
        {% include 'core/componentes/navbar.html' %}
    
        <!-- Contenido principal -->
        <main class="flex-grow-1">
            {% block contenido %}
            {% endblock contenido %}
        </main>
    
        <!-- Footer -->
        <footer class="bg-dark text-white text-center py-1">
            {% include 'core/componentes/footer.html' %}
        </footer>
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

src/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<div class="container px-4 px-lg-5">
    <!-- Heading Row-->
    <div class="row gx-2 gx-lg-2 align-items-center my-5">
        <div class="col-lg-5">
            <img src="{% static 'core/img/imagen.webp' %}" alt="imagen" class="img-fluid rounded shadow-lg" style="width: 200px; height: 200px;margin-left: 150px;">
        </div>
        <div class="col-lg-7">
            <h1 class="font-weight-light" style="margin-right: 150px;">Gestión Financiera Familiar</h1>
            <p style="margin-right: 150px;">Bienvenido a la herramienta que te permite visualizar los ingresos y gastos tuyos y de tu familia de manera simple y práctica.</p>
        </div>
    </div>
</div>

<div class="row g-4">
    {% url 'gestion:usuario_list' as ruta_usuario_list %}
    {% include 'core/componentes/card.html' with titulo="Usuarios" contenido="Ingrese para ver los miembros de su familia" ruta=ruta_usuario_list %}

    {% url 'gestion:transaccion_list' as ruta_transaccion_list %}
    {% include 'core/componentes/card.html' with titulo="Operaciones" contenido="Ingrese para ver los ingresos y gastos ingresados por cada miembro" ruta=ruta_transaccion_list %}

    {% url 'gestion:informe_list' as ruta_informe_list %}
    {% include 'core/componentes/card.html' with titulo="Informes" contenido="Ingrese para ver los resumenes de Ingresos y Gastos" ruta=ruta_informe_list %}
</div>

{% endblock contenido %}

src/core/templates/core/index_crudo.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Small Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Services</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" alt="..." /></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light">Business Name or Tagline</h1>
                    <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
                    <a class="btn btn-primary" href="#!">Call to Action!</a>
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card One</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Two</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex natus at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore voluptates quos eligendi labore.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Three</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>




<div>
    <a href="{% url 'gestion:usuario_list' %}"><button>Mostrar Usuarios</button></a>
    <a href="{% url 'gestion:transaccion_list' %}"><button>Mostrar Transacciones</button></a>
    <a href="{% url 'gestion:informe_list' %}"><button>Mostrar Informes</button></a>
</div>
<br>
<div>
    <form action="{% url 'core:perfil' %}" method="post">
        {% csrf_token %}
        <button type="submit" style="background:none;border:none;color: blueviolet;">Modificar Usuario</button>
    </form>
</div>

<div>
    <form action="{% url 'core:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" style="background:none;border:none;color: blueviolet;">Cerrar Sesión</button>
    </form>
</div>

src/core/templates/core/inicio.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<div class="container px-4 px-lg-5">
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
            <img src="{% static 'core/img/imagen.webp' %}" alt="imagen" class="img-fluid rounded shadow-lg" style="width: 450px; height: 450px;margin-left: 150px;">
        </div>
        <div class="col-lg-5">
            <h1 class="font-weight-light" style="margin-right: 150px;">Gestión Financiera Familiar</h1>
            <p style="margin-right: 150px;">Bienvenido a la herramienta que te permite visualizar los ingresos y gastos tuyos y de tu familia de manera simple y práctica.</p>
            <a class="btn btn-primary" href="{% url 'core:login' %}">Iniciar sesión</a>
        </div>
    </div>
</div>
{% endblock contenido %}

src/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block contenido %}
<div class="row justify-content-center">
    <div class="col-md-6 col-lg-5">
        <div class="card shadow-lg">
            <div class="card-body p-5">
                <div class="text-center mb-4">
                    <h2 class="fw-bold">Inicio de sesión</h2>
                    <p class="text-muted">Ingresa tus credenciales para continuar</p>
                </div>

                <form method="POST" class="bg-light p-4 rounded shadow">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block w-100 mt-3" style="background-color: black; border-color: black;">Iniciar sesión</button>
                </form>
            <br>    
            <p>¿No tienes una cuenta? 
            <a href="{% url 'core:register' %}">Registrate aquí</a>
            </div>
        </div>
    </div>
</div>

{% endblock contenido %}

src/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block contenido %}
<div class="row justify-content-center">
    <div class="col-md-6 col-lg-5">
        <div class="card shadow-lg">
            <div class="card-body p-5">
                <div class="text-center mb-4">
                    <h2 class="fw-bold">Ha cerrado Sesión</h2>
                    <br>
                    <p class="text-muted">Esperamos que haya tenido una buena experiencia</p>
                    <br>
                    <p class="text-muted">Inicie sesión para ingresar nuevamente</p>
                <a href="{% url 'core:login' %}">Iniciar sesión</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock contenido %}

src/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block contenido %}
<div class="row justify-content-center">
    <div class="col-md-6 col-lg-5">
        <div class="card shadow-lg">
            <div class="card-body p-5">
                <div class="text-center mb-4">
                    <h2 class="fw-bold">Creación de usuario</h2>
                    <p class="text-muted">Ingrese dos veces la misma contraseña para su validación</p>
                </div>

                <form method="post" class="bg-light p-4 rounded shadow">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-primary btn-block w-100 mt-3" style="background-color: black; border-color: black;">Crear Usuario</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock contenido %}