src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('gestion/', include("gestion.urls")),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path
from .views import (inicio, index, about, CustomLoginView, CustomRegisterView, UpdateProfileViwe)
from django.contrib.auth.views import LogoutView


app_name = "core"

urlpatterns = [
    path('', inicio, name='inicio'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('profile/', UpdateProfileViwe.as_view(), name='perfil'),
    path('logout', LogoutView.as_view(template_name="core/logout.html"), name='logout'),
    path('index/', index, name='index'),
    path('about/', about, name='about'),

]

src/gestion/urls.py
from django.urls import path
from .views_models import transaccion, usuario, informe

app_name = "gestion"

urlpatterns = [
    path("usuario/list/", usuario.UsuarioListView.as_view(), name="usuario_list"),
    path("usuario/create/", usuario.UsuarioCreateView.as_view(), name="usuario_create"),
    path("usuario/update/<int:pk>", usuario.UsuarioUpdateView.as_view(), name="usuario_update"),
    path("usuario/detail/<int:pk>", usuario.UsuarioDetailView.as_view(), name="usuario_detail"),
    path("usuario/delete/<int:pk>/", usuario.UsuarioDeleteView.as_view(), name="usuario_delete"),
    ]

urlpatterns += [
    path("transaccion/list/", transaccion.TransaccionListView.as_view(), name="transaccion_list"),
    path("transaccion/create/", transaccion.TransaccionCreateView.as_view(), name="transaccion_create"),
    path("transaccion/update/<int:pk>", transaccion.TransaccionUpdateView.as_view(), name="transaccion_update"),
    path("transaccion/detail/<int:pk>", transaccion.TransaccionDetailView.as_view(), name="transaccion_detail"),
    path("transaccion/delete/<int:pk>", transaccion.TransaccionDeleteView.as_view(), name="transaccion_delete"),]

urlpatterns += [
    path("informe/list/", informe.InformeListView.as_view(), name="informe_list"),
    path("informe/create/", informe.InformeCreateView.as_view(), name="informe_create"),
    path("informe/update/<int:pk>", informe.InformeUpdateView.as_view(), name="informe_update"),
    path("informe/detail/<int:pk>", informe.InformeDetailView.as_view(), name="informe_detail"),
    path("informe/delete/<int:pk>/", informe.InformeDeleteView.as_view(), name="informe_delete"),
    ]

src/core/models.py
from django.db import models

# Create your models here.

src/core/forms.py
from typing import Any
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = AuthenticationForm
        fields = ['username','password']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {'username': ''}
    
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]

src/core/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm, CustomUserCreationForm, UserProfileForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_not_required
from django.utils.decorators import method_decorator

@login_not_required
def inicio(request: HttpRequest) -> HttpResponse:
    return render(request, "core/inicio.html")

def index(request: HttpRequest) -> HttpResponse:
    return render(request, "core/index.html")

@login_not_required
def about(request: HttpRequest) -> HttpResponse:
    return render(request,"core/about.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'core/login.html'
    success_url = reverse_lazy('core:index')

@method_decorator(login_not_required, name='dispatch')
class CustomRegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')

class UpdateProfileViwe(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/perfil.html'
    success_url = reverse_lazy('core:index') 
    def get_object(self):
        return self.request.user

src/core/templates/core/componentes/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ contenido }}</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="{{ruta}}" style="background-color: mediumorchid; border-color: mediumorchid;">Ir...</a></div>
    </div>
</div>

src/core/templates/core/componentes/footer.html
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Aylen Poschner - Comisión 60095 - Python</p></div>
</footer>

src/core/templates/core/componentes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">¡Bienvenido!</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href={% url 'core:index'%}>Inicio</a></li>             
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">About Me</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'gestion:transaccion_list' %}">Operaciones</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'gestion:informe_list' %}">Informes</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'gestion:usuario_list' %}">Miembros</a></li>
                <li class="nav-item">
                    <form action="{% url 'core:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="nav-link btn btn-link" type="submit">Cerrar Sesión</button>
                    </form>
                    
                {% else %}
                    <li><a class="nav-link active" aria-current="page" href={% url 'core:inicio'%}>Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">About Me</a></li>                       
                {% endif %}
                
                </li>
            </ul>
        </div>
    </div>
</nav